// Imports
import type { Metadata } from "next";

// Dynamic Pages Generated Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const DynamicPages: any = async ({params}: any) => {

	return (
		<div className="">
			Enter
		</div>
	);
};

export default DynamicPages;
