import type { Metadata } from "next";
import type {AppProps} from "next/app";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


// Firebase
import initializeFirebase from "@/firebase/firebase";


// Context Providers
import FirebaseContextProvider from "@/context/providers/FirebaseContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const App = async ({children}: AppProps | any) => {

  // FIREBASE //
	// Initializing Firebase
  initializeFirebase();
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <FirebaseContextProvider> */}
          {children}
        {/* </FirebaseContextProvider> */}
      </body>
    </html>
  );
}

export default App;
