import type { Metadata } from "next";
import type {AppProps} from "next/app";

// Global Styling
import "@/styles/globals.scss";

// Context Providers
import FirebaseUserProvider from "@/context/providers/FirebaseContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const App = async ({children}: AppProps | any) => {

  
  return (
    <html lang="en">
      <body >
          <FirebaseUserProvider>{children}</FirebaseUserProvider>
      </body>
    </html>
  );
}

export default App;
