import type { Metadata } from "next";
import type {AppProps} from "next/app";

// Global Styling
import "@/styles/globals.scss";

// Firebase
import initializeFirebase from "@/firebase/firebase";


// Context Providers
import FirebaseContextProvider from "@/context/providers/FirebaseContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const App = async ({children}: AppProps | any) => {

  // FIREBASE //
	// Initializing Firebase
  initializeFirebase();
  
  return (
    <html lang="en">
      <body >
        {/* <FirebaseContextProvider> */}
          {children}
        {/* </FirebaseContextProvider> */}
      </body>
    </html>
  );
}

export default App;
